[package]
name = "dinero"
version = "0.0.1"
edition = "2021"

[workspace]
members = ["core"]


[dependencies]
core = { path = "./core" }

[dev-dependencies]
insta = { version = "1.17.1", features = ["backtrace", "redactions"] }
