name: Publish Crate

on:
  release:
    types: [published]
  workflow_dispatch:
    description: "Publish release"

jobs:
  is-release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || startsWith(github.event.release.tag_name, 'v') }}
    steps:
      - run: echo "Release tag should be vX.Y.Z"
  release:
    runs-on: ubuntu-latest
    needs: is-release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
